module.exports = {
  color: {
    offWhite: { value: "#FAFAFA" },
    charcoal: { value: "#2D3232" },
    warmGrey: { value: "#E6DCDC" },
    violet: {
      bright: {
        _: { value: "#825FFF" },
        "01": { value: "#E3E8F6" },
        "02": { value: "{color.violet.pastel._.value}" },
        "03": { value: "{color.violet.mid._.value}" },
        "04": { value: "{color.violet.bright._.value}" },
        "05": { value: "#6449C4" },
        "06": { value: "#443185" },
        "07": { value: "#443185" },
      },
      brightAccessible: {
        _: { value: "#7C57FF" },
        "01": { value: "#E3E8F6" },
        "02": { value: "{color.violet.pastel._.value}" },
        "03": { value: "{color.violet.mid._.value}" },
        "04": { value: "{color.violet.brightAccessible._.value}" },
        "05": { value: "#6449C4" },
        "06": { value: "#443185" },
      },
      mid: {
        _: { value: "#9088FF" },
        "01": { value: "#E3E8F6" },
        "02": { value: "{color.violet.pastel._.value}" },
        "03": { value: "{color.violet.mid._.value}" },
        "04": { value: "{color.violet.brightAccessible._.value}" },
        "05": { value: "#6449C4" },
        "06": { value: "#443185" },
      },
      pastel: {
        _: { value: "#C8D1ED" },
        "01": { value: "#E3E8F6" },
        "02": { value: "{color.violet.pastel._.value}" },
        "03": { value: "{color.violet.mid._.value}" },
        "04": { value: "{color.violet.brightAccessible._.value}" },
        "05": { value: "#6449C4" },
        "06": { value: "#443185" },
      },
    },
    green: {
      bright: {
        _: { value: "#00C8A5" },
        "01": { value: "#E3E8F6" },
        "02": { value: "{color.violet.pastel._.value}" },
        "03": { value: "{color.violet.mid._.value}" },
        "04": { value: "{color.violet.bright._.value}" },
        "05": { value: "#6449C4" },
        "06": { value: "#443185" },
        "07": { value: "#443185" },
      },
      mid: {
        _: { value: "#80DBB7" },
        "01": { value: "#E3E8F6" },
        "02": { value: "{color.violet.pastel._.value}" },
        "03": { value: "{color.violet.mid._.value}" },
        "04": { value: "{color.violet.bright._.value}" },
        "05": { value: "#6449C4" },
        "06": { value: "#443185" },
        "07": { value: "#443185" },
      },
      pastel: {
        _: { value: "#BEE1D4" },
        "01": { value: "#E3E8F6" },
        "02": { value: "{color.violet.pastel._.value}" },
        "03": { value: "{color.violet.mid._.value}" },
        "04": { value: "{color.violet.bright._.value}" },
        "05": { value: "#6449C4" },
        "06": { value: "#443185" },
        "07": { value: "#443185" },
      },
    },
    yellow: {
      bright: {
        _: { value: "#FFB400" },
        "01": { value: "#E3E8F6" },
        "02": { value: "{color.violet.pastel._.value}" },
        "03": { value: "{color.violet.mid._.value}" },
        "04": { value: "{color.violet.bright._.value}" },
        "05": { value: "#6449C4" },
        "06": { value: "#443185" },
        "07": { value: "#443185" },
      },
      mid: {
        _: { value: "#EEC779" },
        "01": { value: "#E3E8F6" },
        "02": { value: "{color.violet.pastel._.value}" },
        "03": { value: "{color.violet.mid._.value}" },
        "04": { value: "{color.violet.bright._.value}" },
        "05": { value: "#6449C4" },
        "06": { value: "#443185" },
        "07": { value: "#443185" },
      },
      pastel: {
        _: { value: "#E1D4BE" },
        "01": { value: "#E3E8F6" },
        "02": { value: "{color.violet.pastel._.value}" },
        "03": { value: "{color.violet.mid._.value}" },
        "04": { value: "{color.violet.bright._.value}" },
        "05": { value: "#6449C4" },
        "06": { value: "#443185" },
        "07": { value: "#443185" },
      },
    },
    red: {
      bright: {
        _: { value: "#FF375A" },
        "01": { value: "#E3E8F6" },
        "02": { value: "{color.violet.pastel._.value}" },
        "03": { value: "{color.violet.mid._.value}" },
        "04": { value: "{color.violet.bright._.value}" },
        "05": { value: "#6449C4" },
        "06": { value: "#443185" },
        "07": { value: "#443185" },
      },
      mid: {
        _: { value: "#FF8066" },
        "01": { value: "#E3E8F6" },
        "02": { value: "{color.violet.pastel._.value}" },
        "03": { value: "{color.violet.mid._.value}" },
        "04": { value: "{color.violet.bright._.value}" },
        "05": { value: "#6449C4" },
        "06": { value: "#443185" },
        "07": { value: "#443185" },
      },
      pastel: {
        _: { value: "#E1C4BE" },
        "01": { value: "#E3E8F6" },
        "02": { value: "{color.violet.pastel._.value}" },
        "03": { value: "{color.violet.mid._.value}" },
        "04": { value: "{color.violet.bright._.value}" },
        "05": { value: "#6449C4" },
        "06": { value: "#443185" },
        "07": { value: "#443185" },
      },
    },
    grey: {
      "00": { value: "#FFFFFF" },
      "01": { value: "{color.offWhite.value}" },
      "02": { value: "#F7F7F7" },
      "03": { value: "#EAEBEB" },
      "04": { value: "#D5D6D6" },
      "05": { value: "#C0C2C2" },
      "06": { value: "#B3B5B5" },
      "07": { value: "#ABADAD" },
      "08": { value: "#969898" },
      09: { value: "#818484" },
      10: { value: "#6C7070" },
      11: { value: "#5F6363" },
      12: { value: "#575B5B" },
      13: { value: "#424747" },
      14: { value: "{color.charcoal.value}" },
      15: { value: "#1A1D1D" },
    },
  },
};
