module.exports = {
  transparent: "var(--base-color-transparent)",
  current: "var(--base-color-current)",
  white: "var(--base-color-white)",
  black: {
    DEFAULT: "var(--color-black-default)",
    superdark: "var(--color-black-superdark)",
    100: "var(--color-black-100)",
    95: "var(--color-black-95)",
    90: "var(--color-black-90)",
    85: "var(--color-black-90)",
    80: "var(--color-black-80)",
    70: "var(--color-black-70)",
    60: "var(--color-black-60)",
    50: "var(--color-black-50)",
    40: "var(--color-black-40)",
    30: "var(--color-black-30)",
    20: "var(--color-black-20)",
    10: "var(--color-black-10)",
    5: "var(--color-black-5)",
    0: "var(--color-black-0)",
    warm: "var(--color-black-warm)",
  },
  violet: {
    90: "var(--color-violet-90)",
    70: "var(--color-violet-70)",
    60: "var(--color-violet-60)",
    50: "var(--color-violet-50)",
    40: "var(--color-violet-40)",
    20: "var(--color-violet-20)",
  },
  green: {
    90: "var(--color-green-90)",
    80: "var(--color-green-80)",
    75: "var(--color-green-80)",
    70: "var(--color-green-70)",
    60: "var(--color-green-60)",
    50: "var(--color-green-50)",
    40: "var(--color-green-40)",
    20: "var(--color-green-20)",
  },

  yellow: {
    90: "var(--color-yellow-90)",
    70: "var(--color-yellow-70)",
    60: "var(--color-yellow-60)",
    50: "var(--color-yellow-50)",
    40: "var(--color-yellow-40)",
    20: "var(--color-yellow-20)",
  },

  red: {
    90: "var(--color-red-90)",
    70: "var(--color-red-70)",
    65: "var(--color-red-70)",
    60: "var(--color-red-60)",
    50: "var(--color-red-50)",
    40: "var(--color-red-40)",
    20: "var(--color-red-20)",
  },
};
