/**
 * IMPORTANT
 * None of these tokens should be exported for use by design system adopters.
 * They are simply a palette of the values we use that make up out brand.
 */

module.exports = {
  color: {
    offWhite : { value: "#FAFAFA", comment: "deprecating" },
    charcoal : { value: "#2D3232" },
    warmGrey : { value: "#E6DCDC" },
    violet: {
      bright: {
        _ : { value: "#825FFF" },
        // 1 : { value: "#E3E8F6" },
        // 2 : { value: "#C8D1ED" },
        // 3 : { value: "#9088FF" },
        // 4 : { value: "{color.violet.bright._.value}" },
        // 5 : { value: "#6449C4" },
        // 6 : { value: "#443185" },
      },
      brightAccessible: {
        _ : { value: "#7C57FF" },
        1 : { value: "#E3E8F6" },
        2 : { value: "#C8D1ED" },
        3 : { value: "#9088FF" },
        4 : { value: "{color.violet.brightAccessible._.value}" },
        5 : { value: "#6449C4" },
        6 : { value: "#443185" },
      },
      mid: {
        _ : { value: "#9088FF" },
        // 1 : { value: "#E3E8F6" },
        // 2 : { value: "#C8D1ED" },
        // 3 : { value: "{color.violet.mid._.value}" },
        // 4 : { value: "#7C57FF" },
        // 5 : { value: "#6449C4" },
        // 6 : { value: "#443185" },
      },
      pastel: {
        _ : { value: "#C8D1ED" },
        // 1 : { value: "#E3E8F6" },
        // 2 : { value: "{color.violet.pastel._.value}" },
        // 3 : { value: "#9088FF" },
        // 4 : { value: "#7C57FF" },
        // 5 : { value: "#6449C4" },
        // 6 : { value: "#443185" },
      },
    },
    green: {
      bright: {
        _ : { value: "#00C8A5" },
        1 : { value: "#DEF0E9" },
        2 : { value: "#BEE1D4" },
        3 : { value: "#80DBB7" },
        4 : { value: "{color.green.bright._.value}" },
        5 : { value: "#00A084" },
        6 : { value: "#006452" },
      },
      mid: {
        _ : { value: "#80DBB7" },
        // 1 : { value: "#E3E8F6" },
        // 2 : { value: "#BEE1D4" },
        // 3 : { value: "{color.violet.mid._.value}" },
        // 4 : { value: "#00C8A5" },
        // 5 : { value: "#6449C4" },
        // 6 : { value: "#443185" },
      },
      pastel: {
        _ : { value: "#BEE1D4" },
        // 1 : { value: "#E3E8F6" },
        // 2 : { value: "{color.violet.pastel._.value}" },
        // 3 : { value: "#80DBB7" },
        // 4 : { value: "#00C8A5" },
        // 5 : { value: "#6449C4" },
        // 6 : { value: "#443185" },
      },
    },
    yellow: {
      bright: {
        _ : { value: "#FFB400" },
        1 : { value: "#F0E9DE" },
        2 : { value: "#E1D4BE" },
        3 : { value: "#EEC779" },
        4 : { value: "{color.yellow.bright._.value}" },
        5 : { value: "#E6A200" },
        6 : { value: "#CC9000" },
      },
      mid: {
        _ : { value: "#EEC779" },
        // 1 : { value: "#E3E8F6" },
        // 2 : { value: "#E1D4BE" },
        // 3 : { value: "{color.violet.mid._.value}" },
        // 4 : { value: "#FFB400" },
        // 5 : { value: "#6449C4" },
        // 6 : { value: "#443185" },
      },
      pastel: {
        _ : { value: "#E1D4BE" },
        // 1 : { value: "#E3E8F6" },
        // 2 : { value: "{color.violet.pastel._.value}" },
        // 3 : { value: "#EEC779" },
        // 4 : { value: "#FFB400" },
        // 5 : { value: "#6449C4" },
        // 6 : { value: "#443185" },
      },
    },
    red: {
      bright: {
        _ : { value: "#FF375A" },
        1 : { value: "#F0E1DE" },
        2 : { value: "#E1C4BE" },
        3 : { value: "#FF8066" },
        4 : { value: "{color.red.bright._.value}" },
        5 : { value: "#CC2C48" },
        6 : { value: "#992136" },
      },
      mid: {
        _ : { value: "#FF8066" },
        1 : { value: "#F0E1DE" },
        2 : { value: "#E1C4BE" },
        3 : { value: "#FF8066" },
        4 : { value: "{color.red.bright._.value}" },
        5 : { value: "#CC2C48" },
        6 : { value: "#992136" },
      },
      pastel: {
        _ : { value: "#E1C4BE" },
        // 1 : { value: "#E3E8F6" },
        // 2 : { value: "{color.violet.pastel._.value}" },
        // 3 : { value: "#FF8066" },
        // 4 : { value: "#FF375A" },
        // 5 : { value: "#6449C4" },
        // 6 : { value: "#443185" },
      },
    },
    grey: {
      1        : { value: "#FFFFFF" },
      2        : { value: "{color.offWhite.value}" },
      3        : { value: "#F7F7F7" },
      4        : { value: "#EAEBEB" },
      5        : { value: "#D5D6D6" },
      6        : { value: "#C0C2C2" },
      7        : { value: "#B3B5B5" },
      8        : { value: "#ABADAD" },
      9        : { value: "#969898" },
      10       : { value: "#818484" },
      11       : { value: "#6C7070" },
      12       : { value: "#5F6363" },
      13       : { value: "#575B5B" },
      14       : { value: "#424747" },
      15       : { value: "{color.charcoal.value}" },
      16       : { value: "#1A1D1D" },
      lightest : { value: "{color.grey.1.value}" },
      darkest  : { value: "{color.grey.15.value}" },
    },
  },
};
