/**
 * Any of the brand colors we want to use in the UI are reassigned to new,
 * more semantic variables here. This has a handful of benefits, most noteable
 * is flexible theming.
 */

module.exports = {
  color: {
    base     : { value: "{color.grey.10.value}" },
    lightest : { value: "{color.grey.lightest.value}" },
    darkest  : { value: "{color.grey.darkest.value}" },
    inverse: {
      _ : { value: "{color.inverse.10.value}" },
      10 : { value: "{color.grey.150.value}" },
      20 : { value: "{color.grey.140.value}" },
      30 : { value: "{color.grey.130.value}" },
    },
    neutral: {
      _ : { value: "{color.neutral.20.value}" },
      hover: { value: "{color.neutral.30.value}"},
      pressed: { value: "{color.neutral.40.value}"},
      inverse: {value: "{color.darkest.value}"},
      10  : { value: "{color.grey.10.value}" },
      20  : { value: "{color.grey.20.value}" },
      30  : { value: "{color.grey.30.value}" },
      40  : { value: "{color.grey.40.value}" },
      50  : { value: "{color.grey.50.value}" },
      60  : { value: "{color.grey.60.value}" },
      70  : { value: "{color.grey.70.value}" },
      80  : { value: "{color.grey.80.value}" },
      90  : { value: "{color.grey.90.value}" },
      100 : { value: "{color.grey.100.value}" },
      110 : { value: "{color.grey.110.value}" },
      120 : { value: "{color.grey.120.value}" },
      130 : { value: "{color.grey.130.value}" },
      140 : { value: "{color.grey.140.value}" },
      150 : { value: "{color.grey.150.value}" },
      160 : { value: "{color.grey.160.value}" },
    },
    strong: {
      _ : { value: "{color.neutral.130.value}" },
      hover: { value: "color.neutral.140.value"},
      pressed: { value: "color.neutral.160.value"},
      inverse: {value: "color.darkest.value"},
    },
    interactive: {
      _ : { value: "{color.interactive.40.value}" },
      hover: { value: "{color.interactive.50.value}"},
      pressed: { value: "{color.interactive.60.value}"},
      inverse: {value: "{color.lightest.value}"},
      10 : { value: "{color.violet.brightAccessible.10.value}" },
      20 : { value: "{color.violet.brightAccessible.20.value}" },
      30 : { value: "{color.violet.brightAccessible.30.value}" },
      40 : { value: "{color.violet.brightAccessible.40.value}" },
      50 : { value: "{color.violet.brightAccessible.50.value}" },
      60 : { value: "{color.violet.brightAccessible.60.value}" },
    },
    positive: {
      _ : { value: "{color.positive.40.value}" },
      hover: { value: "{color.positive.50.value}"},
      pressed: { value: "{color.positive.60.value}"},
      inverse: {value: "{color.lightest.value}"},
      10 : { value: "{color.green.bright.10.value}" },
      20 : { value: "{color.green.bright.20.value}" },
      30 : { value: "{color.green.bright.30.value}" },
      40 : { value: "{color.green.bright.40.value}" },
      50 : { value: "{color.green.bright.50.value}" },
      60 : { value: "{color.green.bright.60.value}" },
    },
    warning: {
      _ : { value: "{color.warning.40.value}" },
      hover: { value: "{color.warning.50.value}"},
      pressed: { value: "{color.warning.60.value}"},
      inverse: {value: "{color.lightest.value}"},
      10 : { value: "{color.yellow.bright.10.value}" },
      20 : { value: "{color.yellow.bright.20.value}" },
      30 : { value: "{color.yellow.bright.30.value}" },
      40 : { value: "{color.yellow.bright.40.value}" },
      50 : { value: "{color.yellow.bright.50.value}" },
      60 : { value: "{color.yellow.bright.60.value}" },
    },
    negative: {
      _ : { value: "{color.negative.40.value}" },
      hover: { value: "{color.negative.50.value}"},
      pressed: { value: "{color.negative.60.value}"},
      inverse: {value: "{color.lightest.value}"},
      10 : { value: "{color.red.bright.10.value}" },
      20 : { value: "{color.red.bright.20.value}" },
      30 : { value: "{color.red.bright.30.value}" },
      40 : { value: "{color.red.bright.40.value}" },
      50 : { value: "{color.red.bright.50.value}" },
      60 : { value: "{color.red.bright.60.value}" },
    },
  },
};
