module.exports = {
  palette: {
    ui: {
      color: {
        neutral: {
          "01": { value: "white", attributes: { category: "color" } },
          "02": { value: "#00FF00", attributes: { category: "color" } },
          "03": {
            value: "{palette.brand.color.offWhite.value}",
            attributes: { category: "color" },
          },
          "04": { value: "#00FF00", attributes: { category: "color" } },
          "05": { value: "#00FF00", attributes: { category: "color" } },
          "06": { value: "#00FF00", attributes: { category: "color" } },
          "07": { value: "#00FF00", attributes: { category: "color" } },
          "08": { value: "#00FF00", attributes: { category: "color" } },
          "09": { value: "#00FF00", attributes: { category: "color" } },
          10: { value: "#00FF00", attributes: { category: "color" } },
          11: { value: "#00FF00", attributes: { category: "color" } },
          12: { value: "#00FF00", attributes: { category: "color" } },
          13: { value: "#00FF00", attributes: { category: "color" } },
          14: { value: "#00FF00", attributes: { category: "color" } },
          15: { value: "#00FF00", attributes: { category: "color" } },
          16: { value: "#00FF00", attributes: { category: "color" } },
          17: { value: "#00FF00", attributes: { category: "color" } },
          18: {
            value: "{palette.brand.color.charcoal.value}",
            attributes: { category: "color" },
          },
          19: { value: "#00FF00", attributes: { category: "color" } },
          20: { value: "black", attributes: { category: "color" } },
        },
        interactive: {
          "01": { value: "#00FF00", attributes: { category: "color" } },
          "02": { value: "#00FF00", attributes: { category: "color" } },
          "03": { value: "#00FF00", attributes: { category: "color" } },
          "04": { value: "#00FF00", attributes: { category: "color" } },
          "05": { value: "#00FF00", attributes: { category: "color" } },
          "06": { value: "#00FF00", attributes: { category: "color" } },
          "07": { value: "#00FF00", attributes: { category: "color" } },
          "08": { value: "#00FF00", attributes: { category: "color" } },
          "09": { value: "#00FF00", attributes: { category: "color" } },
          10: { value: "#00FF00", attributes: { category: "color" } },
        },
        critical: {
          "01": { value: "#00FF00", attributes: { category: "color" } },
          "02": { value: "#00FF00", attributes: { category: "color" } },
          "03": { value: "#00FF00", attributes: { category: "color" } },
          "04": { value: "#00FF00", attributes: { category: "color" } },
          "05": { value: "#00FF00", attributes: { category: "color" } },
          "06": { value: "#00FF00", attributes: { category: "color" } },
          "07": { value: "#00FF00", attributes: { category: "color" } },
          "08": { value: "#00FF00", attributes: { category: "color" } },
          "09": { value: "#00FF00", attributes: { category: "color" } },
          10: { value: "#00FF00", attributes: { category: "color" } },
        },
        warning: {
          "01": { value: "#00FF00", attributes: { category: "color" } },
          "02": { value: "#00FF00", attributes: { category: "color" } },
          "03": { value: "#00FF00", attributes: { category: "color" } },
          "04": { value: "#00FF00", attributes: { category: "color" } },
          "05": { value: "#00FF00", attributes: { category: "color" } },
          "06": { value: "#00FF00", attributes: { category: "color" } },
          "07": { value: "#00FF00", attributes: { category: "color" } },
          "08": { value: "#00FF00", attributes: { category: "color" } },
          "09": { value: "#00FF00", attributes: { category: "color" } },
          10: { value: "#00FF00", attributes: { category: "color" } },
        },
        positive: {
          "01": { value: "#00FF00", attributes: { category: "color" } },
          "02": { value: "#00FF00", attributes: { category: "color" } },
          "03": { value: "#00FF00", attributes: { category: "color" } },
          "04": { value: "#00FF00", attributes: { category: "color" } },
          "05": { value: "#00FF00", attributes: { category: "color" } },
          "06": { value: "#00FF00", attributes: { category: "color" } },
          "07": { value: "#00FF00", attributes: { category: "color" } },
          "08": { value: "#00FF00", attributes: { category: "color" } },
          "09": { value: "#00FF00", attributes: { category: "color" } },
          10: { value: "#00FF00", attributes: { category: "color" } },
        },
        beta: {
          "01": { value: "#00FF00", attributes: { category: "color" } },
          "02": { value: "#00FF00", attributes: { category: "color" } },
          "03": { value: "#00FF00", attributes: { category: "color" } },
          "04": { value: "#00FF00", attributes: { category: "color" } },
          "05": { value: "#00FF00", attributes: { category: "color" } },
          "06": { value: "#00FF00", attributes: { category: "color" } },
          "07": { value: "#00FF00", attributes: { category: "color" } },
          "08": { value: "#00FF00", attributes: { category: "color" } },
          "09": { value: "#00FF00", attributes: { category: "color" } },
          10: { value: "#00FF00", attributes: { category: "color" } },
        },
      },
    },
  },
};
