name: Continuous Integration

on:
  pull_request:
    branches:
      - "main"
      - "next"

jobs:
  continuous-integration:
    name: Validate PR Name
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.6
        env:
          - GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
