name: Release

on:
  workflow_dispatch:
    branches:
      - "main"
  push:
    branches:
      - "next"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: write

    steps:
      - name: Checkout default branch
        uses: actions/checkout@v2

      - name: Use Node.js 16 (npm repository)
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"

      - name: Cache dependencies
        id: npm_cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: node16-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.npm_cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build Arcade
        run: npm run build

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPMTOKEN: ${{ secrets.NPM_TOKEN }}
